### ISSUE TITLE
virtualenv

### ISSUE THREAD

**Issue by shahpr** [pspealman/uorfseqr#1]
The virtual environment cannot be activated because the `uorf_env` folder is missing the `bin` folder. 

Also, there's a typo in folder name in the manual - `urofenv` instead of `uorf_env`

**Comment by pspealman** [comment]
Hi Premal, my apologies for the delay in the reply, I had missed the 're-opened' notification.

The virtualenv is not always portable ([a known issue](https://virtualenv.pypa.io/en/latest/userguide/#making-environments-relocatable)) and caused some frustrations in an earlier deployment. 

I've added it back in and made a note (and a correction to the manual) that it may not a solution for all users.
